console.log("HELLO WORLD")
console.log("how are u?")
console.log("My self MOOSA")
console.log("I m 20year")
console.log("I have done inter")
console.log("Now a days my university going on as well as I am learning about typescript")
console.log("INSALLAH as soon i will acheive my all goals/desires and lets become a panther of typescript")
console.log("THANK YOU SO MUCH FOR GIVING ME YOUR PRECIOUS TIME")
console.log("ALLAH HAFIZ")